---
title: "week_3_exercises"
author: "Lindsey Greenhill"
date: "2/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

df <- read.table("http://www.stat.columbia.edu/~gelman/arm/examples/pyth/exercise2.1.dat", header = TRUE)

# using head to get the first 40 observations

df_train <- df %>% head(40)

# using tail to get the last 20 observations

df_test <- df %>% tail(20) %>%
  select(x1,x2)


fit_1 <- lm(y ~ x1 + x2, data = df_train)


summary(fit_1)

# the intercept is equal to 1.31, the x1 coefficient is equal to .514, the x2
# coefficient is equal to .806. In context this means that the average value of
# y when x1 and x2 are both 0 is 1.31. For every 1 unit increase in x1, y
# increases by .514 on average, holding x2 constant. For every 1 unit increase
# in x2, y increased by .806 on average, holding x1 constant. The R squared value is about .97, meaning that the model accounts for about 97% of variation. 

y_vs_x1 <- ggplot(df_train, aes(x = x1, y = y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Y vs x1") +
  theme_classic()

y_vs_x2 <- ggplot(df_train, aes(x = x2, y = y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_classic()

# doing residual plots. These plots show the actual values of x1 plotted against
# the residual of x1 in the above model. The horizontal line is at 0, meaning
# that the observed x1 and the predicted x1 were the same.

x1_fit <- lm(y ~ x1, data = df_train)
x1_res <- resid(x1_fit)
x2_fit <- lm(y ~ x2, data = df_train)
x2_res <- resid(x2_fit)

{
plot(df_train$x1, x1_res,
                    ylab = "Residuals",
                    xlab = "x1",
                    main = "x1 Residuals")
abline(0,0)
}

{
plot(df_train$x2, x2_res,
                    ylab = "Residuals",
                    xlab = "x2",
                    main = "x2 Residuals")
abline(0,0)
}

# making predictions for the test data


predictions_fit_1 <- predict(fit_1, newdata = df_test)


```

